package aliU

import "encoding/json"

// Mapify converts any struct to a json friendly map of string to interface
// it expects the thing to have autogenerated json tags
// float64 are supported while ints are not
// Damn and embedded strucs are not flattened by default :p
func Mapify(thing interface{}) (map[string]interface{}, error) {
	var mapified map[string]interface{}
	b, err := json.Marshal(thing)
	if err != nil {
		return mapified, err
	}
	err = json.Unmarshal(b, &mapified)
	return mapified, err
}
